site_name: Mathod
site_url: https://blog.mathod.fr
repo_url: https://github.com/Mathod95/docs
repo_name: Mathod95/docs
edit_uri: edit/main/docs/

nav:
  - HOME: index.md
  - Kuberentes: kubernetes/index.md
  - Argo: 
    - argo/index.md
    - cd: argo/cd/index.md
    - events: argo/events/index.md
    - workflows: argo/workflows/index.md
    - rollouts: argo/rollouts/index.md
  - Crossplane: crossplane/index.md
  - Awesome: awesome.md
  - Tags: tags.md
  - Blog: # https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.blog_dir-documentation--blog
    - blog/index.md
  - About me: about-me/index.md

theme:
  icon:
    repo: fontawesome/brands/github
  #font:
  #  text: JetBrains Sans
  #  code: JetBrains Code
  name: material
  language: fr
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips

markdown_extensions:
  - abbr # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#abbreviations
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      toc_depth: 6
      permalink: true
  - meta
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: embed
          class: embed
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - open-in-new-tab               # https://github.com/JakubAndrysek/mkdocs-open-in-new-tab
  - search:
      lang: fr
  - social                        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
  - blog
  - tags
  - git-revision-date-localized:  # https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      enable_creation_date: true
  #- git-committers:               # https://github.com/byrnereese/mkdocs-git-committers-plugin
  #    repository: Mathod95/docs
  #    branch: main
  #    token:
  #- mkdocs-video                 # https://github.com/soulless-viewer/mkdocs-video
  #- drawio-exporter              # https://github.com/LukeCarrier/mkdocs-drawio-exporter
  - glightbox                     # https://github.com/blueswen/mkdocs-glightbox
  - toggle-sidebar:               # https://github.com/six-two/mkdocs-toggle-sidebar-plugin
      enabled: True
      show_navigation_by_default: true
      show_toc_by_default: true
      theme: material
      toggle_button: all
  - user-defined-values:
      keywords:
        YOUR_AWS_REGION:
          placeholder: e.g. ap-southeast-2
        YOUR_AWS_ACCOUNT_ID:
          placeholder: e.g. 12355224536
  #- link-embeds:                  # https://github.com/Aetherinox/mkdocs-link-embeds
  #    enabled: true
  #    name_default: "Untitled Link"
  #    desc_default: "No description found"
  #    image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
  #    image_disabled: false
  #    favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
  #    favicon_disabled: false
  #    favicon_size: 25
  #    target: "blank"
  #    accent: "FFFFFF1A"
  #    verbose: false

extra:
  analytics:
    provider: google
    property: G-FY4MN6NVXN
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mathod95
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mathod/

extra_css:
  - stylesheets/link-embeds.css